# Generated by Django 4.2.4 on 2023-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventory_manufacturer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="manufacturer",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="item_code",
            new_name="manufacturer_part_number",
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
