# Generated by Django 4.2.4 on 2024-01-04 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_rename_manufacturer_inventory_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="barcode",
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
