# Generated by Django 4.2.4 on 2024-01-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventory_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="category",
            field=models.CharField(default="empty", max_length=300),
            preserve_default=False,
        ),
    ]
